version: '3.7'
services:
  app:
    container_name: frontend
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
