version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3030:3030"
    networks:
      - webapp
    restart: always
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/app:/app
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend/backend:/app_backend
    networks:
      - webapp
      - database
    restart: always
    container_name: backend_app

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_transcendence
    ports:
      - "31415:5432"
    #volumes:
    #  - ./database-data:/
    networks:
      - database
    restart: always
    container_name: db_app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - database
    restart: always
    container_name: pgadmin

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
